// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:acadex/assignment/assignment_model.dart';
import 'package:acadex/attendance/attendance_module_model.dart';
import 'package:acadex/attendance/lecture_model.dart';
import 'package:acadex/exam/exam_model.dart';
import 'package:acadex/gpa/gpa_module_model.dart';
import 'package:acadex/gpa/semester_model.dart';
import 'package:acadex/profile/profile_model.dart';
import 'package:acadex/timetable/timetable_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AssignmentAdapter());
    registerAdapter(AttendanceModuleAdapter());
    registerAdapter(ExamAdapter());
    registerAdapter(GpaModuleAdapter());
    registerAdapter(LectureAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(SemesterAdapter());
    registerAdapter(TimetableModuleAdapter());
    registerAdapter(TimetableSlotAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AssignmentAdapter());
    registerAdapter(AttendanceModuleAdapter());
    registerAdapter(ExamAdapter());
    registerAdapter(GpaModuleAdapter());
    registerAdapter(LectureAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(SemesterAdapter());
    registerAdapter(TimetableModuleAdapter());
    registerAdapter(TimetableSlotAdapter());
  }
}
