// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:acadex/attendance/attendance_module_model.dart';
import 'package:acadex/attendance/lecture_model.dart';
import 'package:acadex/profile/profile_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceModuleAdapter());
    registerAdapter(LectureAdapter());
    registerAdapter(ProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceModuleAdapter());
    registerAdapter(LectureAdapter());
    registerAdapter(ProfileAdapter());
  }
}
